// // Code generated by prismic-ts-codegen. DO NOT EDIT.

// import type * as prismic from "@prismicio/client";

// type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

// type ConfigurationDocumentDataSlicesSlice = ConfigurationSlice

// /**
//  * Content for Configuration documents
//  */
// interface ConfigurationDocumentData {
// 	/**
// 	 * Title field in *Configuration*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: configuration.title
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	title: prismic.KeyTextField;
	
// 	/**
// 	 * Short Description field in *Configuration*
// 	 *
// 	 * - **Field Type**: Rich Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: configuration.short_description
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
// 	 */
// 	short_description: prismic.RichTextField;
	
// 	/**
// 	 * Description field in *Configuration*
// 	 *
// 	 * - **Field Type**: Rich Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: configuration.description
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
// 	 */
// 	description: prismic.RichTextField;
	
// 	/**
// 	 * Slice Zone field in *Configuration*
// 	 *
// 	 * - **Field Type**: Slice Zone
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: configuration.slices[]
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#slices
// 	 */
// 	slices: prismic.SliceZone<ConfigurationDocumentDataSlicesSlice>;/**
// 	 * Meta Title field in *Configuration*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: configuration.meta_title
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	meta_title: prismic.KeyTextField;
	
// 	/**
// 	 * Meta Description field in *Configuration*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: configuration.meta_description
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	meta_description: prismic.KeyTextField;
// }

// /**
//  * Configuration document from Prismic
//  *
//  * - **API ID**: `configuration`
//  * - **Repeatable**: `false`
//  * - **Documentation**: https://prismic.io/docs/custom-types
//  *
//  * @typeParam Lang - Language API ID of the document.
//  */
// export type ConfigurationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ConfigurationDocumentData>, "configuration", Lang>;

// /**
//  * Item in *Footer Navigation → Links*
//  */
// export interface FooterNavigationDocumentDataLinksItem {
// 	/**
// 	 * Label field in *Footer Navigation → Links*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: footer_navigation.links[].label
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	label: prismic.KeyTextField;
	
// 	/**
// 	 * Link field in *Footer Navigation → Links*
// 	 *
// 	 * - **Field Type**: Link
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: footer_navigation.links[].link
// 	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
// 	 */
// 	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
// }

// /**
//  * Content for Footer Navigation documents
//  */
// interface FooterNavigationDocumentData {
// 	/**
// 	 * Homepage field in *Footer Navigation*
// 	 *
// 	 * - **Field Type**: Link
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: footer_navigation.homepage
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
// 	 */
// 	homepage: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
// 	/**
// 	 * Links field in *Footer Navigation*
// 	 *
// 	 * - **Field Type**: Group
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: footer_navigation.links[]
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#group
// 	 */
// 	links: prismic.GroupField<Simplify<FooterNavigationDocumentDataLinksItem>>;
// }

// /**
//  * Footer Navigation document from Prismic
//  *
//  * - **API ID**: `footer_navigation`
//  * - **Repeatable**: `false`
//  * - **Documentation**: https://prismic.io/docs/custom-types
//  *
//  * @typeParam Lang - Language API ID of the document.
//  */
// export type FooterNavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FooterNavigationDocumentData>, "footer_navigation", Lang>;

// /**
//  * Item in *Navigation → Links*
//  */
// export interface NavigationDocumentDataLinksItem {
// 	/**
// 	 * Label field in *Navigation → Links*
// 	 *
// 	 * - **Field Type**: Title
// 	 * - **Placeholder**: Optional - Label for the link
// 	 * - **API ID Path**: navigation.links[].label
// 	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
// 	 */
// 	label: prismic.TitleField;
	
// 	/**
// 	 * Link field in *Navigation → Links*
// 	 *
// 	 * - **Field Type**: Link
// 	 * - **Placeholder**: Link for navigation item
// 	 * - **API ID Path**: navigation.links[].link
// 	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
// 	 */
// 	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
// }

// /**
//  * Content for Navigation documents
//  */
// interface NavigationDocumentData {
// 	/**
// 	 * Homepage field in *Navigation*
// 	 *
// 	 * - **Field Type**: Link
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: navigation.homepage
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
// 	 */
// 	homepage: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
// 	/**
// 	 * Links field in *Navigation*
// 	 *
// 	 * - **Field Type**: Group
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: navigation.links[]
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#group
// 	 */
// 	links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
// }

// /**
//  * Navigation document from Prismic
//  *
//  * - **API ID**: `navigation`
//  * - **Repeatable**: `false`
//  * - **Documentation**: https://prismic.io/docs/custom-types
//  *
//  * @typeParam Lang - Language API ID of the document.
//  */
// export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;

// type PageDocumentDataSlicesSlice = ContactSlice | HeroSlice | QuoteSlice | TextSlice | ImageSlice | ImageCardsSlice | TextWithImageSlice

// /**
//  * Content for Page documents
//  */
// interface PageDocumentData {
// 	/**
// 	 * Title field in *Page*
// 	 *
// 	 * - **Field Type**: Title
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: page.title
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
// 	 */
// 	title: prismic.TitleField;
	
// 	/**
// 	 * Parent field in *Page*
// 	 *
// 	 * - **Field Type**: Content Relationship
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: page.parent
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
// 	 */
// 	parent: prismic.ContentRelationshipField<"page">;
	
// 	/**
// 	 * Slice Zone field in *Page*
// 	 *
// 	 * - **Field Type**: Slice Zone
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: page.slices[]
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#slices
// 	 */
// 	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;/**
// 	 * Meta Title field in *Page*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: A title of the page used for social media and search engines
// 	 * - **API ID Path**: page.meta_title
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	meta_title: prismic.KeyTextField;
	
// 	/**
// 	 * Meta Description field in *Page*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: A brief summary of the page
// 	 * - **API ID Path**: page.meta_description
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	meta_description: prismic.KeyTextField;
	
// 	/**
// 	 * Meta Image field in *Page*
// 	 *
// 	 * - **Field Type**: Image
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: page.meta_image
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#image
// 	 */
// 	meta_image: prismic.ImageField<never>;
// }

// /**
//  * Page document from Prismic
//  *
//  * - **API ID**: `page`
//  * - **Repeatable**: `true`
//  * - **Documentation**: https://prismic.io/docs/custom-types
//  *
//  * @typeParam Lang - Language API ID of the document.
//  */
// export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

// type SeatDocumentDataSlicesSlice = ImageCardsSlice

// /**
//  * Content for Seat documents
//  */
// interface SeatDocumentData {
// 	/**
// 	 * Slice Zone field in *Seat*
// 	 *
// 	 * - **Field Type**: Slice Zone
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: seat.slices[]
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#slices
// 	 */
// 	slices: prismic.SliceZone<SeatDocumentDataSlicesSlice>;/**
// 	 * Meta Title field in *Seat*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: A title of the page used for social media and search engines
// 	 * - **API ID Path**: seat.meta_title
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	meta_title: prismic.KeyTextField;
	
// 	/**
// 	 * Meta Description field in *Seat*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: A brief summary of the page
// 	 * - **API ID Path**: seat.meta_description
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	meta_description: prismic.KeyTextField;
	
// 	/**
// 	 * Meta Image field in *Seat*
// 	 *
// 	 * - **Field Type**: Image
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: seat.meta_image
// 	 * - **Tab**: SEO & Metadata
// 	 * - **Documentation**: https://prismic.io/docs/field#image
// 	 */
// 	meta_image: prismic.ImageField<never>;
// }

// /**
//  * Seat document from Prismic
//  *
//  * - **API ID**: `seat`
//  * - **Repeatable**: `false`
//  * - **Documentation**: https://prismic.io/docs/custom-types
//  *
//  * @typeParam Lang - Language API ID of the document.
//  */
// export type SeatDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SeatDocumentData>, "seat", Lang>;

// /**
//  * Content for Settings documents
//  */
// interface SettingsDocumentData {
// 	/**
// 	 * Site Title field in *Settings*
// 	 *
// 	 * - **Field Type**: Title
// 	 * - **Placeholder**: Title of the site
// 	 * - **API ID Path**: settings.siteTitle
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
// 	 */
// 	siteTitle: prismic.TitleField;
	
// 	/**
// 	 * Show products in subcategories field in *Settings*
// 	 *
// 	 * - **Field Type**: Boolean
// 	 * - **Placeholder**: *None*
// 	 * - **Default Value**: true
// 	 * - **API ID Path**: settings.show_products_in_subcategories
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#boolean
// 	 */
// 	show_products_in_subcategories: prismic.BooleanField;
	
// 	/**
// 	 * Site logo field in *Settings*
// 	 *
// 	 * - **Field Type**: Image
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: settings.site_logo
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#image
// 	 */
// 	site_logo: prismic.ImageField<"small" | "icon">;/**
// 	 * Currency Name field in *Settings*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: settings.currency_name
// 	 * - **Tab**: Currency
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	currency_name: prismic.KeyTextField;
	
// 	/**
// 	 * Currency Image field in *Settings*
// 	 *
// 	 * - **Field Type**: Image
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: settings.currency_image
// 	 * - **Tab**: Currency
// 	 * - **Documentation**: https://prismic.io/docs/field#image
// 	 */
// 	currency_image: prismic.ImageField<"Small">;
	
// 	/**
// 	 * Currency Course field in *Settings*
// 	 *
// 	 * - **Field Type**: Number
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: settings.currency_course
// 	 * - **Tab**: Currency
// 	 * - **Documentation**: https://prismic.io/docs/field#number
// 	 */
// 	currency_course: prismic.NumberField;
// }

// /**
//  * Settings document from Prismic
//  *
//  * - **API ID**: `settings`
//  * - **Repeatable**: `false`
//  * - **Documentation**: https://prismic.io/docs/custom-types
//  *
//  * @typeParam Lang - Language API ID of the document.
//  */
// export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;

// /**
//  * Content for Texts documents
//  */
// interface TextsDocumentData {
// 	/**
// 	 * Copyright footer field in *Texts*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: texts.copyright_footer
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	copyright_footer: prismic.KeyTextField;
	
// 	/**
// 	 * Search seat placeholder field in *Texts*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: texts.search_seat_placeholder
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	search_seat_placeholder: prismic.KeyTextField;
	
// 	/**
// 	 * Search field in *Texts*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: texts.search
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	search: prismic.KeyTextField;
	
// 	/**
// 	 * Load more field in *Texts*
// 	 *
// 	 * - **Field Type**: Text
// 	 * - **Placeholder**: *None*
// 	 * - **API ID Path**: texts.load_more
// 	 * - **Tab**: Main
// 	 * - **Documentation**: https://prismic.io/docs/field#key-text
// 	 */
// 	load_more: prismic.KeyTextField;
// }

// /**
//  * Texts document from Prismic
//  *
//  * - **API ID**: `texts`
//  * - **Repeatable**: `false`
//  * - **Documentation**: https://prismic.io/docs/custom-types
//  *
//  * @typeParam Lang - Language API ID of the document.
//  */
// export type TextsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<TextsDocumentData>, "texts", Lang>;

// export type AllDocumentTypes = ConfigurationDocument | FooterNavigationDocument | NavigationDocument | PageDocument | SeatDocument | SettingsDocument | TextsDocument;

// declare module "@prismicio/client" {
// 	interface CreateClient {
// 		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
// 	}
	
// 	interface CreateWriteClient {
// 		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
// 	}
	
// 	interface CreateMigration {
// 		(): prismic.Migration<AllDocumentTypes>;
// 	}
	
// 	namespace Content {
// 		export type {
// 			ConfigurationDocument,
// 			ConfigurationDocumentData,
// 			ConfigurationDocumentDataSlicesSlice,
// 			FooterNavigationDocument,
// 			FooterNavigationDocumentData,
// 			FooterNavigationDocumentDataLinksItem,
// 			NavigationDocument,
// 			NavigationDocumentData,
// 			NavigationDocumentDataLinksItem,
// 			PageDocument,
// 			PageDocumentData,
// 			PageDocumentDataSlicesSlice,
// 			SeatDocument,
// 			SeatDocumentData,
// 			SeatDocumentDataSlicesSlice,
// 			SettingsDocument,
// 			SettingsDocumentData,
// 			TextsDocument,
// 			TextsDocumentData,
// 			AllDocumentTypes
// 		}
// 	}
// }